# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: [ "*" ] 
  tags:
    include: [ "*" ]
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    id
    echo Hello, world!
    pwd; ls
    ifconfig
# uname -a
# uname -i
# terraform --help
# ansible --help
# aws --help

  displayName: 'Run a multi-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Echo script'
