#trigger:
#  - master
  # branches:
  #   include: [ "*" ] 
  # tags:
  #   include: [ "*" ]
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    terraform init
    terraform plan
    terraform apply -auto-approve
  displayName: 'Create EKS Cluster'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Echo script'



# export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
# export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# export AWS_DEFAULT_REGION=us-west-2
