# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: [ "*" ] 
  tags:
    include: [ "*" ]
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pwd; ls
    terraform init
    terraform plan
# uname -a
# uname -i
# terraform --help
# ansible --help
# aws --help

  displayName: 'Run a multi-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Echo script'



# export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
# export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# export AWS_DEFAULT_REGION=us-west-2
