trigger:
  branches:
    include: [ "*" ] 
  tags:
    include: [ "*" ]
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    terraform init
  displayName: 'terraform init'

- script: |
    terraform plan
  displayName: 'terraform plan'

- script: |
    terraform apply -auto-approve
  displayName: 'Create EKS Cluster'




# export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
# export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# export AWS_DEFAULT_REGION=us-west-2
