apiVersion: v1
kind: ServiceAccount
metadata:
  name: azdevops
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azdevops_role
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling"]
  resources: [""]
  verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azdevops_role_binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azdevops_role
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: ""


# - kind: ServiceAccount
#   name: azdevops
#   namespace: kube-system
#   apiGroup: ""