apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

nodeGroups:
  - name: rs-ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 16
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: rs-ng-2
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 16
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub