apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-1

nodeGroups:
  - name: rs-ng-1
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 16
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      #publicKeyPath: ~/.ssh/ec2_id_rsa.pub
    availabilityZones: ["us-east-1b"]
  - name: rs-ng-2
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 16
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      #publicKeyPath: ~/.ssh/ec2_id_rsa.pub
    availabilityZones: ["us-east-1a"]
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']