apiVersion: v1
kind: ServiceAccount
metadata:
  name: azdevops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azdevops_role
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azdevops_role_binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azdevops_role
subjects:
  - kind: ServiceAccount
    name: azdevops
    namespace: default
    apiGroup: ""

#kubectl config view --minify -o jsonpath={.clusters[0].cluster.server}
#kubectl get serviceAccounts azdevops -o=jsonpath={.secrets[*].name}
#kubectl get secret azdevops-token-9hvl9 -o json

# subjects:
# - kind: User
#   name: jithendar
#   apiGroup: ""