apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deploy-CR
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deploy-CRB
subjects:
- kind: User
  name: system:anonymous
  apiGroup: ""
roleRef:
   apiGroup: ""
   kind: ClusterRole
   name: jenkins-deploy-CR