apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-Deployments
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-Deployments-Binding
subjects:
- kind: User
  name: jithendar
  apiGroup: ""
roleRef:
   apiGroup: ""
   kind: ClusterRole
   name: jenkins-Deployments