apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: jenkins-deployment
subjects:
- kind: User
  name: system:anonymous
  apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: ClusterRole
   name: cluster-admin
   apiGroup: rbac.authorization.k8s.io