apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: jenkins-cluster-admin
subjects:
- kind: User
  name: system:anonymous
  namespace: default
roleRef:
   apiGroup: rbac.authorization.k8s.io/v1
   kind: Role
   name: cluster-admin