apiVersion: v1
kind: Pod
metadata:
  labels:
    run: workstation
  name: workstation
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: jithendar/workstation:2.0
    name: workstation
    resources:
      requests:
        cpu: 500m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 200Mi

