apiVersion: apiVersion: v1
kind: Pod
metadata:
  name: workstation
  labels:
    name: workstation
spec:
  containers:
  - name: workstation
    image: jithendar/workstation:2.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>

